config/routes.rb
Rails.application.routes.draw do
  get 'monstruos/index'

  get 'monstruos/show'

  resources :tweets
  resources :monstruos do
    collection do
      get 'ver'
    end
  end
  
  root 'tweets#default'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/monstruo.rb
class Monstruo < ActiveRecord::Base
	default_scope -> {order("nombre desc")}
  has_many :tweets
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :monstruo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/monstruos_controller.rb
class MonstruosController < ApplicationController
  def index
  end

  def show
  end
  
  def ver    
  end
  
  def destroy
    monstruo = Monstruo.find(params[:id])
    monstruo.destroy
    redirect_to monstruos_path
  end
end

app/controllers/tweets_controller.rb
# encoding = utf-8
class TweetsController < ApplicationController
  
  def default
    
  end
  
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<header>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          
          
          <%= link_to root_path, class: 'navbar-brand' do %>
            <%= image_tag "logo.png", title: "Logo", class: "logo" %>
            Critter
          <% end %>
        </div>
        <div class="collapse navbar-collapse">
          
        </div><!--/.nav-collapse -->
      </div>

    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lab3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container"> 
<%= yield %>
</div>

</body>
</html>

app/views/monstruos/index.html.erb
<!------------------------------------------------------ 
Acá va a ir el listado de monstruos usando los tags  
<ul> y <li>.
Debe tener un título y mostrar el nombre (en negrita) y
la descripción.
------------------------------------------------------>

HACER <br>
/app/views/monstruos/index.html.erb

<!-- punto2 -->
<ul>
	<% Monstruo.all.each do |monstruo| %>
	<li> <strong> Nombre: </strong> <a href= "/monstruos/<%= monstruo.id %>"> <%= monstruo.nombre %>. </a>
		<!-- punto4 
		<% if monstruo.tweets.count > 1 %>
			<p style="color:red;"> Twitero destacado! </p> -->
		<!-- punto5, esta definido en app/assets/stylesheets/monstruos.css.scss-->
		<% if monstruo.tweets.count > 1 %>
			<p class="destacado"> Twitero destacado! </p>
		<strong> Descripcion: </strong> <%= monstruo.descripción %> 
		<!-- punto6 
		<a href="localhost:3000/monstruos"> ELIMINAR </a> -->
		<!-- punto7 -->
		<button type="button" class="btn btn-danger">ELIMINAR</button>
	</li>
</ul>

app/views/monstruos/show.html.erb
Ver un monstruo <br>
/app/views/monstruos/show.html.erb

<!-----------punto3 ------->
<% monstruo=Monstruo.find (params[:id]) %>
<h2> <%= monstruo.nombre %> </h2>
<h1> <%= monstruo.descripcion %> </h1>
<div>
	<img src="/assets/images/monstruo1.jpg" />
</div>

app/views/monstruos/ver.html.erb
<!------------------------------------------------------ 
Debe mostrarse la información del primer monstruo sin
usar el id.
Se debe mostrar el nombre (como título) y la descripción 
(como párrafo).
------------------------------------------------------>

HACER <br>
/app/views/monstruos/ver.html.erb

<!-- punto1 -->
<% monstruo=Monstruo.find(1) %>
<h1> <%= monstruo.nombre %> </h1>
<p> <%= monstruo.descripción %> </p>

app/views/tweets/default.html.erb
<!--
<h1> Bienvenido a Critter </h1>
<h3> ¿Qué desea hacer? </h3>
<ul>
  
  <li> <%= link_to "Listado de Monstruos", monstruos_path %></li>
  <li> <%= link_to "Ver el primer monstruo", ver_monstruos_path %></li>
  
</ul>
-->

<!-- punto8 -->
<h1> Bienvenido a Critter </h1>
<h3> ¿Qué desea hacer? </h3>
<div class="container">
	<div class="row">
		<div class="col-md-6"> Acerca de: <%= link_to "Listado de Monstruos", monstruos_path %> </div>
		<div class="col-md-6"> Links: <%= link_to "Ver el primer monstruo", ver_monstruos_path %> </div>
		<div class="col-md-12"> info aca </div>
	</div>
</div>

app/views/tweets/index.html.erb
<!-- Listado de tweets -->

app/views/tweets/show.html.erb
<!-- Ver un tweet -->